[BASE]
device = cpu
use_txt_feature = false
verbose = true
seed = -1

[OPTIM]
n_objectives = 1
# CMAES, NSGA2, G3PCX, AGEMOEA2, SMSEMOA
algorithm = CMAES
lower_bound = -2
upper_bound = 2
evaluation = 10
population_size = 10
# 24992
dataset_threshold = 0.25
n_dataset_samples = 20